services:
  redis:
    image: redis:7.2   # 或使用最新版 redis:latest
    container_name: my-redis1
    ports:
      - "6379:6379"     # 主機的6379 連到 container 裡的6379
    volumes:
      - redis-data:/data  # 持久化 Redis 資料
    restart: unless-stopped

  mongo:
    image: mongo:7.0       # 或使用最新版 mongo:latest
    container_name: my-mongo1
    ports:
      - "27017:27017"      # 主機的27017 連到 container 裡的27017
    volumes:
      - mongo-data:/data/db  # 持久化 Mongo 資料
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management  # 含有管理介面的版本
    container_name: my-rabbitmq1
    ports:
      - "5672:5672"        # RabbitMQ 用於 AMQP 通訊的 port
      - "15672:15672"      # RabbitMQ 管理介面 (Web UI)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # 持久化 RabbitMQ 資料
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
  rabbitmq-data: